---
- name: Install and configure Apache web server
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache and enable it on boot
      service:
        name: apache2
        state: started
        enabled: true
